"""
Django settings for Kalazio project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

CORS_EXPOSE_HEADERS = ["Content-Type", "cart-items"]
CORS_ALLOW_CREDENTIALS = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-r!v=wc!0gxsnen6%mu-4rno#@b(nr=s-8jk&1)0(c3n1%=zkm9"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition


INSTALLED_APPS = [
    # 'adminlte3',
    # 'adminlte3_theme',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third app
    "django_jalali",
    "taggit",
    "tinymce",
    "rest_framework",
    "rest_framework.authtoken",
    "jdatetime",
    "corsheaders",

    # my app
    "product",
    "brand",
    "order",
    "user",
    "questionAndAnswer",
    "comments",
    "report",
    "adminPanel",
    "contactus",
    'log',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://localhost:8000",
    "http://localhost:8080",
    "http://localhost:3000",
    "http://new.kalazio.ir",
    "http://kalazio.ir",
    "https://new.kalazio.ir",
    "https://kalazio.ir",
    "http://kalazio.com",
    "https://kalazio.com"
]

SADAD_MERCHANT_ID = "000000140329339"
SADAD_SECRET_KEY = "UTW45fvehjSjV7Yfhco84OjC02wB1Pp3"
SADAD_TERMINAL_ID = "24050067"
SADAD_PAYMENT_REQUEST_URL = "https://sadad.shaparak.ir/api/v0/Request/PaymentRequest"
SADAD_PAYMENT_URL = "https://sadad.shaparak.ir/Purchase"
SADAD_PAYMENT_VERIFY_URL = "https://sadad.shaparak.ir/api/v0/Advice/Verify"
PAYMENT_REDIRECT_URL = "https://kalazio.com/payment-result"

ROOT_URLCONF = "Kalazio.urls"

SITE_API_URI = "https://kalazio.com/api"

SITE_URI = "https://kalazio.com"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [""],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Kalazio.wsgi.application"
ASGI_APPLICATION = "Kalazio.asgi.application"

CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "kalaziodb",
        "USER": "gsiadmin",
        "PASSWORD": "qpU92f3UrB6F9H",
        "HOST": "localhost",
        "PORT": "",
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Tiny Mce config

TINYMCE_DEFAULT_CONFIG = {
    "cleanup_on_startup": True,
    "custom_undo_redo_levels": 20,
    "selector": "textarea",
    "theme": "silver",
    "plugins": """
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            """,
    "toolbar1": """
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            """,
    "toolbar2": """
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            """,
    "contextmenu": "formats | link image",
    "menubar": True,
    "statusbar": True,
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "fa-ir"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/usr/local/kalazio/back/static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = "/usr/local/kalazio/back/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "Kalazio.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 50,
}

AUTH_USER_MODEL = "user.User"
# ACCOUNT_AUTHENTICATION_METHOD = 'phone'
# ACCOUNT_PHONE_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = False
