from django.urls import path
from .views import (
    AllProduct,
    AllCategory,
    ProductDetail,
    ProductOfSeller,
    SellerOfBrand,
    DetailOfSeller,
    # InExpensiveProduct,
    # ExpensiveProduct,
    SellerOfProduct,
    CommentsOfProduct,
    QuestionAndAnswerOfProduct,
    RelatedProduct,
    ExpensiveProductOfSeller,
    InExpensiveProductOfSeller,
    LatestProductOfSeller,
    MoreLikeProductOfSeller,
    MoreVisitProductOfSeller,
    MoreSellNumberProductOfSeller,
    AllSeller,
    favorite_product_create,
    FavoriteProductsOfUser,
    favorite_product_delete,
    # applying_product_create,
    GetWarranty,
    ComparisionProduct,
    MoreAdvocateProductOfSeller,
    ReportComment,
    ReportQuestionAndAnswer,
    LikeComment,
    LikeQuestionAndAnswer,
    CommentsTabOfProductDetail,
    SpecialFieldTabOfProductDetail,
    ProductImagesOfUsersOfProduct,
    product_of_category,
    AllMainCategory,
    CategoryChild,
    AddEvidence,
    GetEvidence,
)

urlpatterns = [
    # product api
    path('all-products/', AllProduct.as_view()),
    path('<int:pk>/', ProductDetail.as_view()),
    path('all-category/', AllCategory.as_view()),
    path('add-evidence/', AddEvidence.as_view()),
    path('get-evidence/', GetEvidence.as_view()),
    path('all-main-category/', AllMainCategory.as_view()),
    path('all-category/<int:pk>/', CategoryChild.as_view()),
    path('category/<int:id>/', product_of_category),
    path('products-seller/<int:pk>/', ProductOfSeller.as_view()),
    path('products-comparision/', ComparisionProduct.as_view()),
    path('warranty-seller/<int:pk>/', GetWarranty.as_view()),
    path('seller-of-brand/<int:pk>/', SellerOfBrand.as_view()),
    path('seller-of-product/<int:pk>/', SellerOfProduct.as_view()),
    path('comment-of-product/<int:pk>/', CommentsOfProduct.as_view()),
    path('question-and-answer-of-product/<int:pk>/', QuestionAndAnswerOfProduct.as_view()),
    path('related-product/<int:pk>/', RelatedProduct.as_view()),
    path('favorite-product/<int:pk>/', favorite_product_create),
    path('favorite-product-user/', FavoriteProductsOfUser.as_view()),
    path('favorite-product-delete/<int:pk>/', favorite_product_delete),
    path('comments-tab-of-product/<int:pk>/', CommentsTabOfProductDetail.as_view()),
    path('special-tab-of-product/<int:pk>/', SpecialFieldTabOfProductDetail.as_view()),
    path('images-comment-tab-of-product/<int:pk>/', ProductImagesOfUsersOfProduct.as_view()),

    # seller api
    path('all-seller/', AllSeller.as_view()),
    path('detail-of-seller/<int:pk>/', DetailOfSeller.as_view()),
    path('inexpensive-product-seller/<int:pk>/', InExpensiveProductOfSeller.as_view()),
    path('expensive-product-seller/<int:pk>/', ExpensiveProductOfSeller.as_view()),
    path('latest-product-seller/<int:pk>/', LatestProductOfSeller.as_view()),
    path('liked-product-seller/<int:pk>/', MoreLikeProductOfSeller.as_view()),
    path('visited-product-seller/<int:pk>/', MoreVisitProductOfSeller.as_view()),
    path('more-advocate-product-seller/<int:pk>/', MoreAdvocateProductOfSeller.as_view()),
    path('bestsellers-product-seller/<int:pk>/', MoreSellNumberProductOfSeller.as_view()),

    # report comment and question and answer api
    path('report-comment/', ReportComment.as_view()),
    path('report-question-answer/', ReportQuestionAndAnswer.as_view()),

    # like comment and question and answer api
    path('like-comment/', LikeComment.as_view()),
    path('like-question-answer/', LikeQuestionAndAnswer.as_view()),
]
